This is an easy install guide of the informix database on
raspberry-pi. It is mostly a 1:1 from [[https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=97199][here]].

* Step 1

  Download =Informix Developer Edition for Linux ARM v6 32=. Must be
  that version and must be ARM enabled.

  You can use [[https://www.ibm.com/products/informix/editions][this]] link.

  
* Step 2
 
  - Copy the tar file for installation to your =raspberry= temporary folder.

  #+begin_quote
  scp examplefile yourusername@yourserver:/tmp
  #+end_quote

  I.e. in my case:

  #+BEGIN_SRC sh
  scp ids.12.10.UC12DE.linuxARM32v6.tar pi@raspberrypi:/tmp
  #+END_SRC

  - Then login into your raspberry and do the following:

  - Create a temporary folder for the Informix install files

  #+BEGIN_SRC sh
  mkdir /tmp/ifxinstall
  #+END_SRC

  - Change directory to that folder:

  #+begin_src sh
  cd /tmp/ifxinstall
  #+end_src

  -  Extract the Informix tar file into the ifxinstall folder - wait a
     bit until everything is unpacked and do not interrupt:

  #+BEGIN_SRC sh
  tar xvf /tmp/ids.12.10.UC12DE.linuxARM32v6.tar
  #+END_SRC

  - create a new group informix:

  #+BEGIN_SRC sh
  sudo addgroup informix
  #+END_SRC

  -  (Ref:1) Create a new user informix (with the primary group
     informix). During this step you will be asked for a password for
     informix. Please take a note of that password. You will need it
     later.

  #+BEGIN_SRC sh
  sudo adduser --ingroup informix informix
  #+END_SRC

  - Make sure to add the user informix to the /etc/sudoers file by
    adding the following line by using the 'sudo visudo' command:

  #+BEGIN_SRC sh
  informix ALL=(ALL) NOPASSWD: ALL
  #+END_SRC

  - Run the installation script

  #+BEGIN_SRC sh
  sudo ./ids_install
  #+END_SRC

  Follow the UI and enter the following:

     + accept -> 1 RET

     + RET

     + specify directory where to install the products:
       =/opt/IBM/informix1210UC4DE=

     + accept -> 1 (wait a long bit and do not interrupt)

  - Optional: As soon as the installation has successfully finished,
    you can delete the ifxinstall folder and the Informix install tar
    file if you want.

  #+BEGIN_SRC sh
  rm -rf /tmp/ifxinstall
  rm /tmp/ids.12.10.UC4DE.Linux-ARM6.tar
  #+END_SRC

  - Optional, but highly recommended: create the following symbolic link:
  
  #+BEGIN_SRC sh
  sudo ln -s /opt/IBM/informix1210UC4DE /opt/IBM/informix
  #+END_SRC

  - Create the folder which will later contain the Informix database
    files:

  #+BEGIN_SRC sh
  sudo mkdir /opt/IBM/ifxdata
  #+END_SRC

  - Set its ownership and permissions:

  #+BEGIN_SRC sh
  sudo chown informix:informix /opt/IBM/ifxdata
  sudo chmod 770 /opt/IBM/ifxdata
  #+END_SRC

  
* Step 3 Configuration and initialization of a new Informix instance


  - Login as the informix user

      #+BEGIN_SRC sh
      su informix 
      #+END_SRC

      And enter your password of (Ref:1).

  - Set the $INFORMIXDIR environment variable to point to the Informix
    install directory (actually to the symbolic link):

      #+BEGIN_SRC sh
export INFORMIXDIR=/opt/IBM/informix
      #+END_SRC

  - Extend the $PATH environment variable:

      #+BEGIN_SRC sh
export PATH=$PATH:$INFORMIXDIR/bin
     #+END_SRC

  - Set the $INFORMIXSERVER environment variable (you can choose any
    name here, but let's use ol_informix1210 for now to keep it
    simple):

      #+BEGIN_SRC sh
export INFORMIXSERVER=ol_informix1210
      #+END_SRC


  - Create a new Informix configuration file:

      #+BEGIN_SRC sh
cp $INFORMIXDIR/etc/onconfig.std $INFORMIXDIR/etc/onconfig
      #+END_SRC

  - Create a new Informix hosts definition file:

      #+BEGIN_SRC sh
cp $INFORMIXDIR/etc/sqlhosts.demo $INFORMIXDIR/etc/sqlhosts
      #+END_SRC

  - Edit the file $INFORMIXDIR/etc/onconfig (with nano, vi or any
    other editor)

    I.e. enter the file via the nano editor (or any other editor)

      #+BEGIN_SRC sh
      nano $INFORMIXDIR/etc/onconfig
      #+END_SRC

    And apply the following *changes* (use the search option ^W (control-W)):

      #+begin_example
ROOTPATH /opt/IBM/ifxdata/rootdbs
DBSERVERNAME	ol_informix1210
LTAPEDEV	/dev/null
TAPEDEV		/dev/null
LOGFILES	10
      #+end_example

    Save the file and exit the editor (Control-O RET; Control-X).
  
  - Edit the file $INFORMIXDIR/etc/sqlhosts

      #+BEGIN_SRC sh
nano $INFORMIXDIR/etc/sqlhosts
      #+END_SRC
      
    And *add* the following line:

      #+BEGIN_SRC sh
ol_informix1210	onsoctcp	localhost	9088
      #+END_SRC

    Note: 9088 is the port which will be used by Informix for the
    client/server communication. You can choose any available port
    you want. Save the file and exit the editor.

  - Create an empty database file and set the correct access mode:

  #+BEGIN_SRC sh
touch /opt/IBM/ifxdata/rootdbs
chmod 660 /opt/IBM/ifxdata/rootdbs
  #+END_SRC

  - Now we are ready to initialize Informix for the first time:

      #+BEGIN_SRC sh
oninit -iv
      #+END_SRC

    The first initialization will take a few minutes and it will
    create a few system databases automatically. You can monitor the
    pogress by doing the following:

      #+BEGIN_SRC sh
tail -f /opt/IBM/informix/tmp/online.log
      #+END_SRC

    Please wait until you see the following entry in the =online.log=
    file before you continue:

      #+begin_quote
'sysadmin' database built successfully     
      #+end_quote
  



  
  
